#!/bin/bash

# This is just a sample wrapper to show ways of running GNU make
# using pmash to derive dependency data. The idea is to tell make
# to use pmash via SHELL, set .SHELLFLAGS to the set of options
# we want it to see, and force make to use a single shell per recipe
# because otherwise the results can get messed up. Adjust as desired.

set -x
make SHELL=pmash .SHELLFLAGS='-o $@.d -c' --eval=.ONESHELL: "$@"
